version: '2'
services:
  reactspringheroku-app:
    image: reactspringheroku
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://reactspringheroku-mariadb:3306/reactspringheroku
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
      - SPRING_DATA_JEST_URI=http://reactspringheroku-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://reactspringheroku-elasticsearch:9200
    ports:
      - 8080:8080
  reactspringheroku-mariadb:
    extends:
      file: mariadb.yml
      service: reactspringheroku-mariadb
  reactspringheroku-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: reactspringheroku-elasticsearch
